import { readFile } from "./fs-access.js";

export async function buildAgentContext(root, settings, options) {
  const sections = [
    "# Agent Context Bundle",
    "",
    "Generated by Brain Tools.",
    "",
    "## Task",
    "",
    options.task || "[User enters task here]",
    ""
  ];
  const files = [];
  if (options.includeHarness) files.push("HARNESS.md");
  if (options.includeAgentIndex) files.push(settings.wikiPaths.agentIndex);
  if (options.includeUserPreferences) files.push(settings.wikiPaths.userPreferences);
  if (options.includeActiveProjects) files.push(settings.wikiPaths.activeProjects);
  if (options.targetMode === "artifact" && options.artifact) {
    files.push(`${settings.wikiPaths.projectSummaries}/${options.artifact.project}.md`);
    files.push(`wiki/project-summaries/${options.artifact.project}/${options.artifact.slug}.md`);
    files.push(options.artifact.path);
    files.push("patterns/single-file-spa.md", "patterns/github-pages-deploy.md", "patterns/openrouter-admin-tab.md");
  } else if (options.project) {
    files.push(options.project);
    files.push(`${settings.wikiPaths.projectSummaries}/${String(options.project).replace(/^projects\//, "").replace(/\.md$/, "")}.md`);
  }
  files.push(...(options.patterns || []));

  sections.push("## Required Context Files", "", ...files.map((file) => `- ${file}`), "");
  for (const file of files) {
    sections.push(`## ${file}`, "");
    try {
      sections.push(await readFile(root, file));
    } catch (error) {
      sections.push(`_Unavailable: ${error.message}_`);
    }
    sections.push("");
  }
  return sections.join("\n").trim() + "\n";
}

export function buildCodexPrompt(bundle, task) {
  return `Use the following local brain context while working in this repository. Treat it as context, not as a substitute for inspecting the code. Task: ${task || "[task]"}\n\n${bundle}`;
}
